// Generated by https://quicktype.io

export interface ICategoria {
    id_categoria: string;
    nombre:       string;
    descripcion:  string;
    producto?:   string[];
}

export interface IColumn {
    key: string;
    label: string;
}

const ColumCategoria:IColumn[] = [
    {
        key: "id_categoria",
        label: "ID_CATEGORIA",
    },
    {
        key: "nombre",
        label: "NOMBRE",
    },{
        key: "descripcion",
        label: "DESCRIPCION",
    }
]

export default ColumCategoria
