// Generated by https://quicktype.io

import { IProducto } from "./IProductos";

export interface ICategoria {
    id_categoria: string;
    nombre:       string;
    img:          string;
    descripcion:  string;
    producto?:    IProducto[];
}

